version: '3.8'

services:
 php:
  image: php:8.3-fpm
  container_name: simplephp-php
  volumes:
  - php-assets:/var/www/html

 nginx:
  image: nginx:alpine
  container_name: simplephp-nginx
  volumes:
  - php-assets:/var/www/html
  - ./nginx-conf:/etc/nginx/conf.d
  depends_on:
  - php
  labels:
  - traefik.enable=true
  - traefik.http.routers.simplephp.rule=Host(`stbsite.justendythings.com`)
  - traefik.http.routers.simplephp.entrypoints=websecure
  - traefik.http.routers.simplephp.tls.certresolver=letsencrypt
  - traefik.http.services.simplephp.loadbalancer.server.port=80

volumes:
  # Define the shared volume
  php-assets: