version: '3.8'

services:
 php:
  image: php:8.3-fpm
  container_name: simplephp-php
  volumes:
  - ./html:/var/www/html

 nginx:
  image: nginx:alpine
  ports:
  - "8080:80"
  container_name: simplephp-nginx
  volumes:
  - ./html:/var/www/html
  - ./default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
  - php