services:
 php:
 image: php:8.3-fpm
 container_name: simplephp-php
 volumes:
 - ./html:/var/www/html
 networks:
 - app-net

 nginx:
 image: nginx:alpine
 container_name: simplephp-nginx
 volumes:
 - ./html:/var/www/html
 - ./default.conf:/etc/nginx/conf.d/default.conf
 depends_on:
 - php
 labels:
 - traefik.enable=true
 - traefik.http.routers.simplephp.rule=Host(`example.com`)
 - traefik.http.routers.simplephp.entrypoints=websecure
 - traefik.http.routers.simplephp.tls.certresolver=letsencrypt
 - traefik.http.services.simplephp.loadbalancer.server.port=80
 networks:
 - app-net
 - traefik-proxy

networks:
 app-net:
 traefik-proxy:
 external: true